### ISSUE TITLE
Problem with BIDS dataset

### ISSUE THREAD

**Issue by pascalhuszar** [s-ccs/course_eeg_WS2020#1]
Dont know if its okay to ask questions/ open issues here, but the syntax highlighting is definitely better on github^^

I have problems with the manually downloaded files, i get the following error message in pycharm:
```
<ipython-input-17-e587fd4b418e>:16: RuntimeWarning: Could not locate a data file of a supported format. This is likely a problem with your BIDS dataset. Please run the BIDS validator on your data. (root=..\local\bids, basename=sub-002_ses-P3_task-P3_eeg). []
  raw = read_raw_bids(bids_path)
```

I'm a bit confused, are we supposed to make a directory `local/bids ` and put these files in there? Or is it a different folder structure?

**Comment by schneijan** [comment]
Hi,
the following directory structure worked for me:

```
exercises
├── ex01    
│   ├── main.py    <-- Implements the solutions for the task
│   ├── ccs_eeg_utils.py
│   ├── ... other stuff
├──local
│   ├── bids
│   │   ├── sub-002
│   │   │   ├── ses-P3
│   │   │   │   ├── eeg
│   │   │   │   │   ├── sub-002_ses-P3_task-P3_channels.tsv
│   │   │   │   │   ├── sub-002_ses-P3_task-P3_eeg.fdt
│   │   │   │   │   ├── sub-002_ses-P3_task-P3_eeg.json
│   │   │   │   │   ├── sub-002_ses-P3_task-P3_eeg.set
│   │   │   │   │   ├── sub-002_ses-P3_task-P3_events.tsv
```

Best regards,
Jan

P.S: The Ilias course seems to be down at the moment

**Comment by behinger** [comment]
Hi!
Thanks @Jan for answering. This is indeed the structure.

You can put the exercises directly in exercises, then you do not need to copy `ccs_eeg_utils.py` manually in each exercise folder (you could also somehow make a package out of it with relative import, but my python skills are not good enough for it).

Best, Bene

PS: Thanks for the Ilias comment, very strange. I put it online again ¯\_(ツ)_/¯

**Comment by pascalhuszar** [comment]
S:.
│   README.md
│   requirements.txt
│
├───exercises
│       ccs_eeg_utils.py
│       ex1_overview.md
│       ex2_filter.md
│       ex3_cleaning.md
│       ex4_BSS.md
│       ex5_erpComponents.md
│       ex_01.ipynb
│
├───local
│   │   _init
│   │
│   └───bids
│       └───sub-002
│           └───ses-P3
│               └───eeg
│                       sub-002_ses-P3_task-P3_channels.tsv
│                       sub-002_ses-P3_task-P3_eeg.fdt
│                       sub-002_ses-P3_task-P3_eeg.json
│                       sub-002_ses-P3_task-P3_eeg.set
│                       sub-002_ses-P3_task-P3_events.tsv
│
└───semesterproject
        grading.md
        overview.md
