### ISSUE TITLE
Evts[x] value is -1. Why? 

### ISSUE THREAD

**Issue by pascalhuszar** [s-ccs/course_eeg_WS2020#5]
I asked this kind of question in the lecture but i asked it in a wrong way.
If i'm printing `evts` i get the follwoing array: 
```python
array([[ 12243,      0,      2],
       [ 14299,      0,      2],
       [ 18819,      0,     22],
       ...,
       [406442,      0,      1],
       [407528,      0,      7],
       [407990,      0,      1]])
```
.. i assume the values correspond to `sample | channel | event_id`.
But if i look in the `events.tsv` the actual values are: 
```python
onset	duration	sample	trial_type	stim_file	value
11.9561	0.0	12244	response	n/a	202
13.9639	0.0	14300	response	n/a	202
18.3779	0.2	18820	stimulus	n/a	45
```
As you can see the values of the sample column is 1 point higher. Should that be?

**Comment by behinger** [comment]
ah! now I understand the question.

I think the reason is that the sample 12244 is indexed in python as sample[12243] because pythonists* like to start counting at 0 and not at sample 1.

Does that make sense?

* and others like c etc., and yes there are reasons in favour of it, but I dont agree :P

**Comment by pascalhuszar** [comment]
Makes sense now :) Thanks for the clarification
